output "db_instance_id"       { value = aws_db_instance.main.id }
output "db_endpoint"          { value = aws_db_instance.main.address }
output "db_port"              { value = aws_db_instance.main.port }
output "db_name"              { value = aws_db_instance.main.db_name }
output "db_arn"               { value = aws_db_instance.main.arn }
output "replica_endpoint"     { value = var.create_replica ? aws_db_instance.replica[0].address : "" }
output "secret_arn"           { value = aws_secretsmanager_secret.rds_credentials.arn }
output "security_group_id"    { value = aws_security_group.rds.id }
output "kms_key_arn"          { value = aws_kms_key.rds.arn }
